version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 🌟 内外网双监听：29092给容器内部用，9092给你宿主机用
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://127.0.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: ai_gateway_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always

  # 🌟 AI 网关核心服务 (API)
  ai-api:
    build: .
    container_name: ai_api_server
    command: ["./api-server"]
    ports:
      - "8080:8080"
      - "9091:9091"
    env_file:
      - .env
    environment:
      # 👇 容器网络环境覆盖配置
      - DB_DSN=root:123456@tcp(mysql:3306)/ai_gateway?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_ADDR=redis:6379
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - mysql
      - redis
      - kafka

  # 🌟 网关 Worker 节点
  ai-worker:
    build: .
    container_name: ai_worker_server
    command: ["./worker-server"]
    env_file:
      - .env
    environment:
      # 👇 容器网络环境覆盖配置
      - DB_DSN=root:123456@tcp(mysql:3306)/ai_gateway?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_ADDR=redis:6379
      - KAFKA_BROKERS=kafka:29092
      # 指向宿主机上的 Mock LLM 服务
      - LLM_BACKUP_URL=http://host.docker.internal:8081/v1/chat/completions
      # 指向同一 Docker 网络下的 API 服务
      - CALLBACK_URL=http://ai-api:8080/api/v1/articles/callback
    depends_on:
      - mysql
      - redis
      - kafka
      - ai-api